name: Update YouTube Videos

on:
  schedule:
    - cron: '0 */6 * * *'  # 6時間ごとに実行
  workflow_dispatch:  # 手動実行も可能

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          
      - name: Install dependencies
        run: bundle install
        
      - name: Update YouTube videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: ruby scripts/update_youtube.rb
        
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add _data/youtube_videos.yml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update YouTube videos" && git push) 